### ISSUE TITLE
Style Y127 - Modules

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#11]
[Discuss](https://github.com/danielyoung/angular-styleguide#modules-1)

**Comment by idooo** [comment]
-1. Not a big deal for me

**Comment by danielyoung** [comment]
-1. Doesn't seem necessary right now. Maybe in the future if a component's main module file gets huge.

**Comment by robsimpkins** [comment]
Are we not already doing this with agic.core and agic.components??

**Comment by danielyoung** [comment]
@robsimpkins It's more about having a module file that's separate from our controllers, services etc. For now we're relaxed about leaving trivial amounts of other stuff in there before we split things out which also means it doesn't make sense for us to name our module files xx.module.js.

Removed this rule.
