### ISSUE TITLE
Style Y128 - Configuration

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#12]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y128)

**Comment by idooo** [comment]
-1
According to my experience in the most cases you have no configuration phase for your module and if you have it's usually one-two lines of code and you should not move it to a separate file. However it would be a good code style to move module config to a separate file if it is really huge but I do not think we need to standardise that

**Comment by danielyoung** [comment]
Agree that separating 2 lines of config into a separate file is overkill; how about we change this to say that config should be split out if it gets too big. ie > ~10 lines.

**Comment by idooo** [comment]
Agree

**Comment by robsimpkins** [comment]
@danielyoung +1

**Comment by danielyoung** [comment]
Added.
