### ISSUE TITLE
Style Y161 - Create an App Module

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#14]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y161)

**Comment by idooo** [comment]
-1
We already have some constructions for dependencies management and app init (app.js, modules.js). I assume when we will start to work on the new project and then probably move of some stuff to core

**Comment by danielyoung** [comment]
+1; I think we're going to have a lot of repeated code tying things together like app.js and modules.js. Whether it's a module or not I think we need to investigate a way to abstract this.

**Comment by robsimpkins** [comment]
I think app.js and modules.js are already rather untidy and we're not even close to finishing the Life Express project. I think steps need to be taken to tidy this up and improve maintainability before we move too far forward.

**Comment by danielyoung** [comment]
Okay, I'll remove this for now but as we build more apps we'll need to solve the issue of our messy app.js & modules.js; something to be mindful of.
