### ISSUE TITLE
Style Y193 - Stubbing and Spying

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#16]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y193)

**Comment by idooo** [comment]
+1
I've used Sinon previously - good lib that will help us write tests

**Comment by danielyoung** [comment]
+1 to use Sinon; already running into places where I need it.

**Comment by robsimpkins** [comment]
I don't really have anything to add to this having not used Sinon before. Happy to go with the consensus.

**Comment by danielyoung** [comment]
Cool, we'll add this then.
