### ISSUE TITLE
Style Y001 - Rule of 1

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#2]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y001-discuss)

**Comment by idooo** [comment]
+1 to leave it as it is

**Comment by danielyoung** [comment]
+1 to leave it as it is too

**Comment by robsimpkins** [comment]
+1 Do we not already do this?

**Comment by danielyoung** [comment]
@robsimpkins I don't think we've made this an explicit rule.

Added this.
