### ISSUE TITLE
Style Y073 - Provide a Unique Directive Prefix

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#3]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y073)

**Comment by idooo** [comment]
+1 to use it. I think it will help us in the future to easily identify our directives in pages' layouts. We already use prefixes for npm components with the same goal

**Comment by danielyoung** [comment]
+1 to add unique directive prefix

**Comment by robsimpkins** [comment]
+1. Would _agic_ seem logical?

**Comment by idooo** [comment]
Yeah, I've created LIFE-78 ticket about that

**Comment by danielyoung** [comment]
Cool, closing as accepted.
