### ISSUE TITLE
Style Y080 - Controller Activation Promises

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#4]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y080-discuss)

**Comment by idooo** [comment]
+1 to use it. I've used it in SC and it helped us to keep some things clear and for example place all the marketing related code and etc to similar places

**Comment by danielyoung** [comment]
+1 Can we call it like 'init' or something rather than 'activate' though?

**Comment by idooo** [comment]
I like 'init'

**Comment by robsimpkins** [comment]
+1

**Comment by danielyoung** [comment]
Added.
