### ISSUE TITLE
Style Y081 - Route Resolve Promises

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#5]
[Discuss](https://github.com/danielyoung/angular-styleguide#route-resolve-promises)

**Comment by idooo** [comment]
-1 
Not so sure that it will work fine with our app core

**Comment by danielyoung** [comment]
-1; same reason

**Comment by robsimpkins** [comment]
I have nothing worthwhile to contribute here. I'm happy going with the consensus again.

**Comment by danielyoung** [comment]
Cool, removed.
