### ISSUE TITLE
Style Y091 - Manually Identify Dependencies

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#6]
[Discuss](https://github.com/danielyoung/angular-styleguide#manually-identify-dependencies)

**Comment by idooo** [comment]
-1
Just want to keep code clear. Mangling during minification does't provide any big benefits + ng-annotate is cool as well if we will use it.

Suggest to inject dependencies in a simple way without arrays and etc:

```
angular
    .module('whatever')
    .controller('MYCtrl', function($scope, $timeout, KittensService) { ... }); 
```

**Comment by danielyoung** [comment]
-1 Hopefully ng-annotate can do this for us...

**Comment by robsimpkins** [comment]
-1. I prefer the setup we have now. It's much cleaner and less repetitive.

**Comment by danielyoung** [comment]
Removed.
