### ISSUE TITLE
Style Y121 - Feature File Names

### ISSUE THREAD

**Issue by danielyoung** [danielyoung/angular-styleguide#9]
[Discuss](https://github.com/danielyoung/angular-styleguide#style-y121)

**Comment by idooo** [comment]
+1 to have it

**Comment by danielyoung** [comment]
+1 to have it

**Comment by robsimpkins** [comment]
+1. I prefer the . format. example.service.js.

I also think we should standardise the function names inside each file. Sometimes it has the name followed by the type, other times not.

**Comment by danielyoung** [comment]
Added. Have made this naming convention explicit in our app structure and component docs.
